.TH gmx-morph 1 "" "VERSION 5.0.5" "GROMACS Manual"
.SH NAME
gmx-morph - Interpolate linearly between conformations

.SH SYNOPSIS
gmx morph [-f1 [<.gro/.g96/...>]] [-f2 [<.gro/.g96/...>]]
          [-o [<.xtc/.trr/...>]] [-or [<.xvg>]] [-n [<.ndx>]]
          [-nice <int>] [-[no]w] [-xvg <enum>] [-ninterm <int>]
          [-first <real>] [-last <real>] [-[no]fit]

.SH DESCRIPTION
\fBgmx morph\fR does a linear interpolation of conformations in order to create intermediates. Of course these are completely unphysical, but that you may try to justify yourself. Output is in the form of a generic trajectory. The number of intermediates can be controlled with the \fB\-ninterm\fR flag. The first and last flag correspond to the way of interpolating: 0 corresponds to input structure 1 while 1 corresponds to input structure 2. If you specify \fB\-first\fR  0 or \fB\-last\fR  1 extrapolation will be on the path from input structure x_1 to x_2. In general, the coordinates of the intermediate x(i) out of N total intermediates correspond to:

x(i) = x_1 + (first+(i/(N\-1))*(last\-first))*(x_2\-x_1)

Finally the RMSD with respect to both input structures can be computed if explicitly selected (\fB\-or\fR option). In that case, an index file may be read to select the group from which the RMS is computed.

.SH OPTIONS
Options to specify input and output files:

.BI "\-f1" " [<.gro/.g96/...>] (conf1.gro) (Input)"
    Structure file: gro g96 pdb brk ent esp tpr tpb tpa

.BI "\-f2" " [<.gro/.g96/...>] (conf2.gro) (Input)"
    Structure file: gro g96 pdb brk ent esp tpr tpb tpa

.BI "\-o" " [<.xtc/.trr/...>] (interm.xtc) (Output)"
    Trajectory: xtc trr cpt trj gro g96 pdb tng

.BI "\-or" " [<.xvg>] (rms-interm.xvg) (Output, Optional)"
    xvgr/xmgr file

.BI "\-n" " [<.ndx>] (index.ndx) (Input, Optional)"
    Index file


Other options:

.BI "\-nice" " <int> (0)"
    Set the nicelevel

.BI "\-[no]w" "  (no)"
    View output \fB.xvg\fR, \fB.xpm\fR, \fB.eps\fR and \fB.pdb\fR files

.BI "\-xvg" " <enum> (xmgrace)"
    xvg plot formatting: xmgrace, xmgr, none

.BI "\-ninterm" " <int> (11)"
    Number of intermediates

.BI "\-first" " <real> (0)"
    Corresponds to first generated structure (0 is input x_1, see above)

.BI "\-last" " <real> (1)"
    Corresponds to last generated structure (1 is input x_2, see above)

.BI "\-[no]fit" "  (yes)"
    Do a least squares fit of the second to the first structure before interpolating


.SH SEE ALSO
.BR gromacs(7)

More information about \fBGROMACS\fR is available at <\fIhttp://www.gromacs.org/\fR>.
