.TH gmx-saxs 1 "" "VERSION 5.0.5" "GROMACS Manual"
.SH NAME
gmx-saxs - Compute small angle X-ray scattering spectra

.SH SYNOPSIS
gmx saxs [-f [<.xtc/.trr/...>]] [-s [<.tpr/.tpb/...>]] [-n [<.ndx>]]
         [-d [<.dat>]] [-sq [<.xvg>]] [-nice <int>] [-b <time>]
         [-e <time>] [-dt <time>] [-xvg <enum>] [-ng <int>]
         [-startq <real>] [-endq <real>] [-energy <real>]

.SH DESCRIPTION
\fBgmx saxs\fR calculates SAXS structure factors for given index groups based on Cromer's method. Both topology and trajectory files are required.

.SH OPTIONS
Options to specify input and output files:

.BI "\-f" " [<.xtc/.trr/...>] (traj.xtc) (Input)"
    Trajectory: xtc trr cpt trj gro g96 pdb tng

.BI "\-s" " [<.tpr/.tpb/...>] (topol.tpr) (Input)"
    Structure+mass(db): tpr tpb tpa gro g96 pdb brk ent

.BI "\-n" " [<.ndx>] (index.ndx) (Input, Optional)"
    Index file

.BI "\-d" " [<.dat>] (sfactor.dat) (Input, Optional)"
    Generic data file

.BI "\-sq" " [<.xvg>] (sq.xvg) (Output)"
    xvgr/xmgr file


Other options:

.BI "\-nice" " <int> (19)"
    Set the nicelevel

.BI "\-b" " <time> (0)"
    First frame (ps) to read from trajectory

.BI "\-e" " <time> (0)"
    Last frame (ps) to read from trajectory

.BI "\-dt" " <time> (0)"
    Only use frame when t MOD dt = first time (ps)

.BI "\-xvg" " <enum> (xmgrace)"
    xvg plot formatting: xmgrace, xmgr, none

.BI "\-ng" " <int> (1)"
    Number of groups to compute SAXS

.BI "\-startq" " <real> (0)"
    Starting q (1/nm)

.BI "\-endq" " <real> (60)"
    Ending q (1/nm)

.BI "\-energy" " <real> (12)"
    Energy of the incoming X\-ray (keV)


.SH SEE ALSO
.BR gromacs(7)

More information about \fBGROMACS\fR is available at <\fIhttp://www.gromacs.org/\fR>.
